hash-format = "sha256"

[[files]]
file = "AI_CONTEXT.md"
hash = "e01044d82bcb99fb0503c49f8851f6ffa6dec6cb5646a1314690bd01c38be80b"

[[files]]
file = "README.md"
hash = "9150a2ab84ffff5fdd2d4655f3327d2e2defef5d8fb801ccf8ab1fa1f76e0bf3"

[[files]]
file = "mods/angelica.pw.toml"
hash = "d1e02ec961d4d77fb5ce6459fe771887d8b5a09fcc0d5f7c1f2b10315831ab15"
metafile = true

[[files]]
file = "mods/applecore.pw.toml"
hash = "a5836f08783eccabdf1f9fb42b5270b2cdd23dd8c1effba2ad6748da2b706f2d"
metafile = true

[[files]]
file = "mods/archaicfix.pw.toml"
hash = "c57697806ba7ff5d4b88011e20cabdbb476a58a1b544cb759032292be4992cba"
metafile = true

[[files]]
file = "mods/betterfps.pw.toml"
hash = "1d7be9acf687897e75921e34c3236d3a78364d140c13b6c9ac4c4293635a6ebc"
metafile = true

[[files]]
file = "mods/codechickencore-unofficial.pw.toml"
hash = "9fb0370845230010306576f5963d80899c2b46514bcb9b7ec4eed8ecc7924394"
metafile = true

[[files]]
file = "mods/codechickenlib-unofficial.pw.toml"
hash = "f68c436801bb4cca5c0fb8a172badea975d5c98d969affa1ea2d7ffa8c8d71de"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "2d8979b5daa642fbc61126aa3dd68387e6e8cbaef875a8aa9d9a470b7f8fe698"
metafile = true

[[files]]
file = "mods/falsepatternlib.pw.toml"
hash = "7a6ccd80f18cbd674eb72014b8725e651c0961f2e742f5549692e05b311af1eb"
metafile = true

[[files]]
file = "mods/fastcraft.pw.toml"
hash = "422af561be79850d7b301261b133bfc8ddcf7eab4c9d2e3934ded3f6fa72bf58"
metafile = true

[[files]]
file = "mods/gregtech6.pw.toml"
hash = "6a6c8d861f148cda4492ec2df4fc40975ce0a4c0902d947f27a867715a557d7e"
metafile = true

[[files]]
file = "mods/gtnhlib.pw.toml"
hash = "a9c82a62c3b80a00b631b415f90e18d73c5c77b8047eff96c10842ff99707ee0"
metafile = true

[[files]]
file = "mods/industrial-craft.pw.toml"
hash = "36eaa1e528a80689fe868f86c4333b7d267fb85c3d429696f0c3f9a6fb90b9b6"
metafile = true

[[files]]
file = "mods/inventory-tweaks.pw.toml"
hash = "61744ee5386e2a558cc599cb04a1f9f5938c4aba72260614c67ff746c753668b"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "b9d8d5fe7ffcae44789420fc91cf07c291d12b4d1a4cb111792bfc24c3c5c5ac"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "c849632fd2348967eb369eaecd93f65de371cd9110650f828f995a4929166ae3"
metafile = true

[[files]]
file = "mods/nei-addons.pw.toml"
hash = "1f1b9809a0e8a144ea2428a67144256fbc9816f4a29a1878b4720558952ad391"
metafile = true

[[files]]
file = "mods/notenoughitems-gtnh.pw.toml"
hash = "e60e11843042294eb79968d180fd92ee0e178471cffd50d6f5c189310988bd33"
metafile = true

[[files]]
file = "mods/unimixins.pw.toml"
hash = "cb026f337dbf7777e573233edca713a96eca54f3b7bab0d3207368b524ff6d2f"
metafile = true

[[files]]
file = "mods/waila-harvestability.pw.toml"
hash = "995bb06d581518cba9d922ba23f2705a7b596b458ce0af1ba23d9c669da4221c"
metafile = true

[[files]]
file = "mods/waila.pw.toml"
hash = "1ce389a8d9488dd7d37490c1498d10412b7430b18cc0faa28f47afc9cf896b57"
metafile = true
