hash-format = "sha256"

[[files]]
file = "README.md"
hash = "fd9b10c61d44dc964249fd20fd9a8264479344eb26dffdd92a26fcdf85ede97b"

[[files]]
file = "mods/applecore.pw.toml"
hash = "a5836f08783eccabdf1f9fb42b5270b2cdd23dd8c1effba2ad6748da2b706f2d"
metafile = true

[[files]]
file = "mods/betterfps.pw.toml"
hash = "1d7be9acf687897e75921e34c3236d3a78364d140c13b6c9ac4c4293635a6ebc"
metafile = true

[[files]]
file = "mods/codechickencore.pw.toml"
hash = "877e37dd1a4313b52e1d40d74fe9abc89658f8cf172263b0f33d0feb15db89b6"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "2d8979b5daa642fbc61126aa3dd68387e6e8cbaef875a8aa9d9a470b7f8fe698"
metafile = true

[[files]]
file = "mods/fastcraft.pw.toml"
hash = "422af561be79850d7b301261b133bfc8ddcf7eab4c9d2e3934ded3f6fa72bf58"
metafile = true

[[files]]
file = "mods/gregtech6.pw.toml"
hash = "6a6c8d861f148cda4492ec2df4fc40975ce0a4c0902d947f27a867715a557d7e"
metafile = true

[[files]]
file = "mods/industrial-craft.pw.toml"
hash = "36eaa1e528a80689fe868f86c4333b7d267fb85c3d429696f0c3f9a6fb90b9b6"
metafile = true

[[files]]
file = "mods/inventory-tweaks.pw.toml"
hash = "61744ee5386e2a558cc599cb04a1f9f5938c4aba72260614c67ff746c753668b"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "b9d8d5fe7ffcae44789420fc91cf07c291d12b4d1a4cb111792bfc24c3c5c5ac"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "c849632fd2348967eb369eaecd93f65de371cd9110650f828f995a4929166ae3"
metafile = true

[[files]]
file = "mods/nei-addons.pw.toml"
hash = "1f1b9809a0e8a144ea2428a67144256fbc9816f4a29a1878b4720558952ad391"
metafile = true

[[files]]
file = "mods/notenoughitems.pw.toml"
hash = "920d279a70b25cad68c4f1c1992f8d4562e2d648402e2f9df013d078d62eae71"
metafile = true

[[files]]
file = "mods/waila-harvestability.pw.toml"
hash = "995bb06d581518cba9d922ba23f2705a7b596b458ce0af1ba23d9c669da4221c"
metafile = true

[[files]]
file = "mods/waila.pw.toml"
hash = "1ce389a8d9488dd7d37490c1498d10412b7430b18cc0faa28f47afc9cf896b57"
metafile = true
