name = "GT6: Modernized"
author = "Agent"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "767ad001a34b719df151c6b77fb458ac36402a44b5da934e8d7f38cde3284043"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"

[options]
acceptable-game-versions = ["1.7", "1.7.10"]
