name = "GT6 Maintainable Pack"
author = "Agent"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b4faf77ec389af9a9abc5f730d5205431d97e6504de58a061d7a3ab1c43dee1"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"

[options]
acceptable-game-versions = ["1.7", "1.7.10"]
