name = "GT6 Maintainable Pack"
author = "Agent"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12cfd6cf47a2e25c144b85dc61d1bb3284c67b142604c780ad3490748d3e740e"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"

[options]
acceptable-game-versions = ["1.7", "1.7.10"]
