name = "GT6 Maintainable Pack"
author = "Agent"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc90ef57a28abcda29fadfc84d161890ce31ca01633ca704d500bd5169bc981e"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"

[options]
acceptable-game-versions = ["1.7", "1.7.10"]
