name = "GT6: Modernized"
author = "Agent"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc104fc3dc992482e475a8328880d7e832337542ad28a59dae0e4c9ed62f0c97"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"

[options]
acceptable-game-versions = ["1.7", "1.7.10"]
