name = "GT6 Maintainable Pack"
author = "Agent"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3869bdd028ce211f44c55ae71ec72b0f6a2e66a8ff1d3e421a2c038cba7b0fc7"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"

[options]
acceptable-game-versions = ["1.7", "1.7.10"]
