name = "GT6 Maintainable Pack"
author = "Agent"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5294727eff7fab70727f4080feb464c1c3eb15a99bc986a46f5bf4ff28de103"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"

[options]
acceptable-game-versions = ["1.7", "1.7.10"]
