name = "GT6: Modernized"
author = "Agent"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89862bef372f80808b9b3b8635356acfaf9a1beb3a8a5a49bfa08d124a522108"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"

[options]
acceptable-game-versions = ["1.7", "1.7.10"]
